### ISSUE TITLE
Incorrect beach entrance coordinates

### ISSUE THREAD

**Issue by GrumpyCrouton** [GrumpyCrouton/SDV-AccessibleTiles#1]
> zkline — Today at 1:42 PM
> The beach entrance provided by the AccessibleTiles  mod is wrong, for some reason. You need to either warp to it or find the coordinates for the real one, which I don't recall at the moment unfortunately.

> GrumpyCrouton — Today at 2:16 PM
> @zkline Are you talking about the beach entrance from the town?

> zkline — Today at 2:20 PM
> Yes.

**Comment by jamestoh-leos** [comment]
Other instance is in the mountain to town and town to mountain.

There is mountain to mine because there is 2 entrance, one is near the quary and the other is near the lake.

Mountain to carpenter house is fine but carpenter to mountain is incorrect.
